[application]

# App (Project) Name
name = "Vapor Manager"

# Dioxus App Default Platform
# desktop, web
default_platform = "desktop"

# `build` & `serve` dist path
out_dir = "dist"

# assets file folder
asset_dir = "public"

[bundle]
identifier = "com.vaporsystems"
publisher = "Vapor Systems"
icon = ["icons/icon.ico"]

[bundle.windows]
icon_path = "icons/icon.ico"
webview_install_mode = { OfflineInstaller = { silent = true } }
allow_downgrades = true
tsp = false

[web.app]

# HTML title tag content
title = "Vapor Manager"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = []

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
